channels = ["conda-forge"]

[deps]
python-duckdb = "=0.9"
tqdm = "=4.66"
pandas = "=2.1"
dask = "=2023.12"
polars = "=0.19"
jupyterlab = "=4.0"
modin-all = "=0.25"
python = "=3.10"
numpy = "=1.26"
vaex = "=4.16"
